[[shell.step]]
type = "dnf"
packages = ["zsh", "tmux"]

#[[shell.step]]
#type = "apt"
#packages = ["zsh", "tmux", "unzip"]

[[shell.step]]
type = "git"
repo = "https://github.com/jandamm/zgenom"
dest = "~"
basename = ".zgenom"

#[[shell.step]]
#type = "apt"
#packages = ["libxcb-shape0-dev", "libxcb-xfixes0-dev"]  # jless dependencies

[[shell.step]]
type = "cargo"
packages = ["tealdeer", "exa", "ripgrep", "jless", "du-dust", "bat"]

[[shell.step]]
type = "link"
source = "dot-files/zshrc"
dest = "~/.zshrc"

[[shell.step]]
type = "link"
source = "dot-files/zprofile"
dest = "~/.zprofile"

[[shell.step]]
type = "link"
source = "dot-files/zshrc.d"
dest = "~/.config"
