[[system.step]]
type = "link"
source = "dot-files/tmux.conf"
dest = "~/.tmux.conf"

[[system.step]]
type = "git"
repo = "https://github.com/tmux-plugins/tpm"
branch = "master"
dest = "~/.tmux/plugins"
