set -g default-terminal "xterm-256color"
set -g default-shell /usr/bin/zsh
set -g mouse on
set -g status off
set -g history-limit 50000
set -s copy-command 'wl-copy'
setw -g mode-keys vi
#set-option -sa terminal-overrides ',screen.xterm-256color:RGB'
set-option -sa terminal-features ',tmux-256color:RGB'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'peikk0/tmux-cssh'
set -g @plugin 'greymd/tmux-xpanes'

# Manipulate Panes
bind ! break-pane -d -n _hidden_pane
bind @ join-pane -h -s "%%"
bind "j" swap-pane -s :.2 -t :.0 \; select-pane -t :.0
bind "k" swap-pane -s :.1 -t :.0 \; select-pane -t :.0

# Pane navigation with Ctrl + arrow keys (no prefix needed)
bind-key -n C-Up select-pane -U
bind-key -n C-Down select-pane -D
bind-key -n C-Left select-pane -L
bind-key -n C-Right select-pane -R

# Create sessions
bind -r "s" display-popup -E "~/bin/tmux-sessionizer"
bind -r "?" run-shell "tmux neww ~/bin/tmux-sessionizer tmp"

# cheatsheet
bind -r i run-shell "tmux neww tmux-cht.sh"
#bind -r j split-window -h -b -l 40% 'watch -t --color -n1 "jj log --color always --template builtin_log_compact --ignore-working-copy"'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
