# path
path=(
    ~/bin
    ~/.local/bin
    ~/.cargo/bin
    ~/.config/fzf/bin
    ~/.poetry/bin
    ~/.mozbuild/git-cinnabar
    ~/.mozbuild/moz-phab/arcanist/bin
    ~/.mozbuild/version-control-tools/git/commands
    ~/.npm-global/bin
    ~/.tmux/plugins/tmux-xpanes/bin
    ~/go/bin
    ~/opt/lua-language-server/bin
    ~/opt/protoc/bin
    /var/lib/flatpak/exports/bin
    $path
)

# Note: WSL does not currently apply umask properly.
if [ "$(umask)" = "000" ]; then
    umask 022
fi

# Set up pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"
