#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    root_dir=~
    selected=$1
else
    root_dir=~/dev
    selected=$(find $root_dir/ -mindepth 1 -maxdepth 1 -type d | xargs -L1 -I{} basename "{}" | sort | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)
selected_root=$root_dir/$selected

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected -c $selected_root
    exit 0
fi

if ! tmux has-session -t=$selected 2> /dev/null; then
    tmux new-session -ds $selected -c $selected_root
fi

tmux switch-client -t $selected
base16_chalk
