#!/usr/bin/env bash

ROOT_DIR=~/dev

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $ROOT_DIR/ -mindepth 1 -maxdepth 1 -type d | xargs -L1 -I{} basename "{}" | sort | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)
selected_root=$ROOT_DIR/$selected

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected -c $selected_root
    exit 0
fi

if ! tmux has-session -t=$selected 2> /dev/null; then
    tmux new-session -ds $selected -c $selected_root
fi

tmux switch-client -t $selected
