#!/usr/bin/env bash

if [[ -z "${TASKCLUSTER_ROOT_URL}" ]]; then
    echo "No Root URL specified; set TASKCLUSTER_ROOT_URL";
    exit 1;
fi

function notify-send() {
    wsl-notify-send.exe --category "$WSL_DISTRO_NAME" "${@}";
}

status_cmd="sh -c \"(taskcluster task status ${1} 2> /dev/null || echo unscheduled) | cut -d' ' -f1\"";
completed_re='^(completed|failed|exception)$'

task_status=$(eval "$status_cmd");
notify-send "Task ${1} is $task_status";
prev_status="$task_status"

while ! [[ $task_status =~ $completed_re ]]
do
    sleep 10;
    task_status=$(eval "$status_cmd");
    if [[ $task_status != "$prev_status" ]]; then
        notify-send "Task ${1} is $task_status";
        prev_status=$task_status
    fi
done
echo "$task_status"
notify-send "Task ${1} is $task_status";
